# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100000)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(max_length=100000)),
                ('set', models.IntegerField(unique=True)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lux.Question'),
        ),
    ]
